import type { Metadata } from 'next';
import styles from './layout.module.css';

export const metadata: Metadata = {
	title: 'Auth',
	description: 'Generated by create next app'
};

export default function AuthLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<main className={styles.authLayout}>
			<section className={styles.auth}>{children}</section>
		</main>
	);
}
