import { primaryFont } from '@shared/fonts';
import type { Metadata } from 'next';
import './global.css';

export const metadata: Metadata = {
	title: 'Chat',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body data-theme='dark' className={primaryFont.className}>
				{children}
			</body>
		</html>
	);
}
